# env PW=${PW} docker-compose up [-d]

version: '2'
services:

  osclient:
    image: mooxe/openstack/osclient
    restart: always
    environment:
      - HOST_KEYSTONE=keystone
      - HOST_GLANCE=glance
      - OS_PASSWORD=${PW}
      - OS_AUTH_URL='http://keystone:35357/v3'
    command: tail -f /dev/null

  db_keystone:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${PW}
      - MYSQL_DATABASE=keystone
      - MYSQL_USER=keystone
      - MYSQL_PASSWORD=${PW}
    ports:
      - 3396:3306/tcp
    command:
      --character-set-server=utf8
      --collation-server=utf8_general_ci
      --default-storage-engine=innodb
      --innodb_file_per_table=on
      --max_connections=4096

  keystone:
    image: mooxe/openstack/keystone
    restart: always
    environment:
      - HOST_KEYSTONE=keystone
      - HOST_DB_KEYSTONE=db_keystone
      - PORT_DB_KEYSTONE=3306
      - OS_PASSWORD=${PW}
      - OS_AUTH_URL='http://keystone:35357/v3'
    ports:
      - 35357:35357/tcp
      - 5000:5000/tcp
    command:
      /usr/bin/env bash -c "/root/keystone/config/connection.sh && tail -f /dev/null"

  db_glance:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${PW}
      - MYSQL_DATABASE=glance
      - MYSQL_USER=glance
      - MYSQL_PASSWORD=${PW}
    ports:
      - 3397:3306/tcp
    command:
      --character-set-server=utf8
      --collation-server=utf8_general_ci
      --default-storage-engine=innodb
      --innodb_file_per_table=on
      --max_connections=4096

  mc_glance:
    image: memcached
    restart: always
    ports:
      - 11211:11211/tcp

  glance:
    image: mooxe/openstack/glance
    restart: always
    environment:
      - HOST_KEYSTONE=keystone
      - HOST_DB_GLANCE=db_glance
      - PORT_DB_GLANCE=3306
      - HOST_MC_GLANCE=mc_glance
      - OS_PASSWORD=${PW}
      - OS_AUTH_URL='http://keystone:35357/v3'
    ports:
      - 9191:9191/tcp
      - 9292:9292/tcp
    command:
      /usr/bin/env bash -c "/root/glance/config/connection.sh && tail -f /dev/null"
